ia32: build fix
Making this function inline causes a weird build error (at least with
gcc-13):

  In static member function
    ‘static void Kmem::init_cpu_arch(Cpu&, Lockless_alloc*)’:
  ...src/kern/ia32/32/kmem-ia32-32.cpp:8:1: error:
    ‘static void Kmem::init_cpu_arch(Cpu&, Lockless_alloc*)’
    causes a section type conflict with
      ‘static void Kmem::map_initial_ram()’
    8 | Kmem::init_cpu_arch(Cpu &cpu, Lockless_alloc *cpu_mem)
      | ^~~~
  ...src/kern/ia32/kmem-ia32.cpp:202:1: note:
    ‘static void Kmem::map_initial_ram()’ was declared here
  202 | Kmem::map_initial_ram()
      | ^~~~

Change-Id: If09aaa8f7c4073b4a5c72bdc84128fe462e4ab4c