ia32/ARM: fix compilation of startup-ia32 with -O0
Gcc -O0 complains about

  src/kern/ia32/startup-ia32.cpp:41:1: error:
  ‘static void Startup::stage1()’ causes a section type conflict with
  ‘static void Utcb_init::init()’

The real problem is that Utcb_init::init() is an (empty) inline function
on ia32 and ARM and are not marked as FIASCO_INIT. But even doing that
doesn't help. Workaround the problem with ALWAYS_INLINE.

Change-Id: Iedf8042b874971122555fc7ad2756fbe4c069a0f